runtime: nodejs22

handlers:
  # Serve all files in /static (JavaScript, CSS, etc.) directly from the build/static directory
  - url: /static
    static_dir: build/static

  # Serve theme.css directly from the root if it exists in build/themes
  - url: /themes
    static_dir: build/themes

  # Serve PDF files from the root of the build directory
  - url: /(.*\.pdf)
    static_files: build/\1
    upload: build/(.*\.pdf)

  # Serve favicon, manifest, and other root-level assets directly
  - url: /(favicon\.ico|manifest\.json|robots\.txt)
    static_files: build/\1
    upload: build/(favicon\.ico|manifest\.json|robots\.txt)

  # Serve other assets in the build directory, like images, icons, etc.
  - url: /(.*\.(ico|png|svg|json|txt|jpg|jpeg|webp))
    static_files: build/\1
    upload: build/(.*\.(ico|png|svg|json|txt|jpg|jpeg|webp))

  # Serve index.html for all other paths to enable client-side routing
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
