runtime: python39
service: backend
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker app:app

env_variables:
  PYTHONPATH: "/workspace"
  GOOGLE_CLOUD_PROJECT: "cardmath-llc"
  SMTP_EMAIL: "support@cardmath.ai"
  ENVIRONMENT: "prod"

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 1

service_account: cardmath-llc@appspot.gserviceaccount.com