runtime: python
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"
env: flex
service: backend
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --timeout 300 app:app

env_variables:
  PYTHONPATH: "/workspace"
  GOOGLE_CLOUD_PROJECT: "cardmath-llc"
  SMTP_EMAIL: "support@cardmath.ai"
  ENVIRONMENT: "development"

beta_settings:
  cloud_sql_instances: cardmath-llc:northamerica-northeast2:cardmathdb

resources:
  cpu: 6
  memory_gb: 12

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
