"""remove unused fields on user and onboarding

Revision ID: 17769cffbb18
Revises: 6d5f10e80e38
Create Date: 2024-12-25 16:57:35.124048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17769cffbb18'
down_revision: Union[str, None] = '6d5f10e80e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding', sa.Column('teller_id', sa.String(), nullable=True))
    op.drop_index('ix_onboarding_token', table_name='onboarding')
    op.create_index(op.f('ix_onboarding_teller_id'), 'onboarding', ['teller_id'], unique=True)
    op.drop_column('onboarding', 'created_at')
    op.drop_column('onboarding', 'is_used')
    op.drop_column('onboarding', 'token')
    op.add_column('users', sa.Column('teller_ids', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_teller_ids'), 'users', ['teller_ids'], unique=False)
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'username')
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_teller_ids'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'teller_ids')
    op.add_column('onboarding', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('onboarding', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('onboarding', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_onboarding_teller_id'), table_name='onboarding')
    op.create_index('ix_onboarding_token', 'onboarding', ['token'], unique=True)
    op.drop_column('onboarding', 'teller_id')
    # ### end Alembic commands ###
