"""add subscription id to user to eager load the subscription object

Revision ID: 777d039fe553
Revises: d78e2da92edd
Create Date: 2025-01-04 13:49:54.488292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777d039fe553'
down_revision: Union[str, None] = 'd78e2da92edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscription_id')
    # ### end Alembic commands ###
