"""smoother onboarding flow user creation

Revision ID: d78e2da92edd
Revises: 17769cffbb18
Create Date: 2024-12-25 23:09:35.372268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78e2da92edd'
down_revision: Union[str, None] = '17769cffbb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('onboarding_associated_user_id_fkey', 'onboarding', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('onboarding', 'associated_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding', sa.Column('associated_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'onboarding', type_='foreignkey')
    op.create_foreign_key('onboarding_associated_user_id_fkey', 'onboarding', 'users', ['associated_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('onboarding', 'user_id')
    # ### end Alembic commands ###
